services:
  web:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html/
    depends_on:
      - php
      - mysql
    networks:
      - app-network
    container_name: helios-web

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/var/www/html/
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "php-fpm-healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3
    container_name: helios-php

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOTPASS:?err}
      MYSQL_DATABASE: ${DB_NAME:?err}
      MYSQL_USER: ${DB_USERNAME:?err}
      MYSQL_PASSWORD: ${DB_PASSWORD:?err}
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql:/var/lib/mysql
    networks:
      - app-network
    container_name: helios-mysql

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
